version: '3.6'

services:

  # mysql:
  #   image: mysql:5.7.21
  #   environment:
  #     MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
  #     MYSQL_DATABASE: mobylis
  #     MYSQL_USER: mobylis-backend
  #     MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
  #   volumes:
  #     - mysql:/var/lib/mysql
  #   secrets:
  #     - mysql_root_password
  #     - mysql_password
  #   ports:
  #     - 3306:3306

  elasticsearch:
    image: mobylis/elasticsearch:latest
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
           memory: 600M
        reservations:
           memory: 600M   
    ports:
      - 9200:9200

volumes: 
  esdata: 

# secrets: 
#   mysql_root_password:
#     external: true
#   mysql_password:
#     external: true