version: '3.6'

services:

 elasticsearch:
    image: mobylis/elasticsearch:latest
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    deploy:
      resources:
        limits:
           memory: 600M
        reservations:
           memory: 600M   
    ports:
      - 9200:9200

  # mobylis-backend:
  #   image: mobylis/backend:latest
  #   environment:
  #     CLOUDINARY_API_KEY: /run/secrets/CLOUDINARY_API_KEY
  #     CLOUDINARY_API_SECRET: /run/secrets/CLOUDINARY_API_SECRET
  #   secrets:
  #     - mysql_password
  #     - SPRING_PROFILE
  #     - CLOUDINARY_API_KEY
  #     - CLOUDINARY_API_SECRET
  #   ports:
  #     - 80:9090

volumes: 
  esdata: 

#secrets: 
#  SPRING_PROFILE:
#    external: true
#  CLOUDINARY_API_KEY:
#    external: true
#  CLOUDINARY_API_SECRET:
#    external: true